replicaCount: 1
clusterName: dav08649-aks
pathBase: /catalog-api

image:
  repository: dav08649/catalog.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: PORT
      value: "80"
  configmap:
    - name: ConnectionStrings__Default
      key: internalurls__sql__server
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 5
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 10
    periodSeconds: 5
    port: 80

