apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webstatus.fullname" . }}
  labels:
    {{- include "webstatus.labels" . | nindent 4 }}
data:
  name__adapter__hc: Adapter HTTP Check
  internalurls__adapter__hc: http://{{ .Values.app.svc.adapter }}/hc
  name__catalog__hc: Catalog HTTP Check
  internalurls__catalog__hc: http://{{ .Values.app.svc.catalog }}/hc
  name__spa__hc: SPA HTTP Check
  internalurls__spa__hc: http://{{ .Values.app.svc.spa }}/hc
  name__webapigw__hc: WEB API Gateway HTTP Check
  internalurls__webapigw__hc: http://{{ .Values.app.svc.webapigw }}/hc