apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webstatus.fullname" . }}
  labels:
    {{- include "webstatus.labels" . | nindent 4 }}
data:
  name__adapter__hc: Adapter HTTP Check
  internalurls__adapter__hc: http://{{ .Values.app.svc.adapter }}/hc
  name__data__hc: Data HTTP Check
  internalurls__data__hc: http://{{ .Values.app.svc.data }}/hc