replicaCount: 1
clusterName: dav08649-aks
pathBase: /adapter-api

image:
  repository: dav08649/adapter.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: PORT
      value: 80

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 5
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 10
    periodSeconds: 5
    port: 80
