{{- $name := include "adapter-api.fullname" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "adapter-api.name" . }}
    chart: {{ template "adapter-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
