apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.catalogsqldb }}
  labels:
    {{- include "catalogsqldb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "catalogsqldb.selectorLabels" . | nindent 4 }}
