{{- $name := include "catalog-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "catalog-api.name" . }}
    chart: {{ template "catalog-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  internalurls__sql__server: Server={{ .Values.app.svc.catalogsqldb }};Database=busagg;User Id=sa;Password=Pass@word
