version: '3.7'

services:
  webapigw:
    image: ${REGISTRY:-dav08649}/webapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateway/Web.Bus.HttpAggregator/Dockerfile

  webstatus:
    image: ${REGISTRY:-dav08649}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: WebStatus/Dockerfile

  webspa:
    image: ${REGISTRY:-dav08649}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/Dockerfile
    depends_on:
      - data-api
      - adapter-api

  data-api:
    image: ${REGISTRY:-dav08649}/data.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Data/Data.API/Dockerfile

  adapter-api:
    image: ${REGISTRY:-dav08649}/adapter.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Adapter/Adapter.API/Dockerfile
