version: '3.7'

services:

  # web-client:
  #   container_name: busweb
  #   build:
  #     context: .
  #     dockerfile: Web/Dockerfile
  #   volumes:
  #     - './Web/Client:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  web-server:
    container_name: spaserver
    build:
      context: .
      dockerfile: Web/Server/Dockerfile
    ports:
      - 3002:5002
