version: '3.7'

services:
  webaggregator:
    image: ${REGISTRY:-bus}/webaggregator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateway/Web.Bus.HttpAggregator/Dockerfile

  webstatus:
    image: ${REGISTRY:-bus}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: WebStatus/Dockerfile

  webspa-server:
    image: ${REGISTRY:-bus}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/Dockerfile
    depends_on:
      - catalog-api
      - adapter-api

  catalog-api:
    image: ${REGISTRY:-bus}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  adapter-api:
    image: ${REGISTRY:-bus}/adapter.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Adapter/Adapter.API/Dockerfile
