version: '3.7'

services:
  webapigw:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - AdapterUrlHC=http://adapter-api/hc
      - DataUrlHC=http://data-api/hc
      - WebSpaUrlHC=http://webspa/hc
      - WebApiGWUrlHC=http://webapigw/hc
    ports:
      - 5110:80

  webstatus:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Adapter HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://adapter-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://data-api/hc
      - HealthChecksUI__HealthChecks__2__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webspa/hc
      - HealthChecksUI__HealthChecks__3__Name=Web Bus Api Gateway
      - HealthChecksUI__HealthChecks__3__Uri=http://webapigw/hc
    ports:
      - "5101:80"

  webspa:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5102:80

  data-api:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/data-api
    ports:
      - "5103:80"

  adapter-api:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/adapter-api
    ports:
      - "5104:80"
