version: '3.7'

services:
  catalogapigw:
    container_name: catalogapigw
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceUrlHC=http://catalog-api/hc
      - ServiceApiName=Catalog API
    volumes:
      - ./ApiGateways/Gateway.CatalogApi:/app/Configuration
    ports:
      - 5111:80

  adapterapigw:
    container_name: adapterapigw
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceUrlHC=http://adapter-api/hc
      - ServiceApiName=Adapter API
    volumes:
      - ./ApiGateways/Gateway.AdapterApi:/app/Configuration
    ports:
      - 5112:80

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Adapter HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://adapter-api/hc

      - HealthChecksUI__HealthChecks__1__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://catalog-api/hc

      - HealthChecksUI__HealthChecks__2__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webspa/hc

      - HealthChecksUI__HealthChecks__3__Name=Catalog API Gateway
      - HealthChecksUI__HealthChecks__3__Uri=http://catalogapigw/hc

      - HealthChecksUI__HealthChecks__4__Name=Adapter API Gateway
      - HealthChecksUI__HealthChecks__4__Uri=http://adapterapigw/hc
    ports:
      - "5101:80"

  webspa:
    container_name: webspa
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5102:80

  catalog-api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/catalog-api
    ports:
      - "5103:80"

  adapter-api:
    container_name: adapter-api
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/adapter-api
    ports:
      - "5104:80"
