version: '3.7'

services:
  # web-client:
  #   container_name: busweb
  #   build:
  #     context: .
  #     dockerfile: Web/Dockerfile
  #   volumes:
  #     - './Web/Client:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  webstatus:
    container_name: webstatus
    build:
      context: .
      dockerfile: WebStatus/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=80
      - PATH_BASE=/webstatus
    ports:
      - "5104:80"

  webspa-server:
    container_name: spaserver
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 3002:5002
    depends_on:
      - catalog-api
      - adapter-api

  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "5101:80"

  adapter-api:
    container_name: adapter-api
    build:
      context: .
      dockerfile: Services/Adapter/Adapter.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=80
      - PATH_BASE=/adapter-api
    ports:
      - "5103:80"
