replicaCount: 1
clusterName: bus-aks
pathBase: /data-api

image:
  repository: dav08649/data-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: PORT
      value: "80"
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80

